version: "3"

services:
  
  dnscrypt-proxy:
    build:
      context: ./dnscrypt-proxy
      network: host
    restart: unless-stopped
    networks:
      dns-net:
        ipv4_address: 172.28.66.2

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'REPLACE'
      DNS1: 172.28.66.2
      DNS2: "no"
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
    networks:
      dns-net:
        ipv4_address: 172.28.66.3
    restart: unless-stopped

networks:
  dns-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.66.0/24
